---
global_params:
  ha_enabled: false
  patches:
    undercloud:
      - change-id: I2e0a40d7902f592e4b7bd727f57048111e0bea36
        project: openstack/tripleo-common
deploy_options:
  containers: true
  os_version: master
  sdn_controller: opendaylight
  odl_version: master
  tacker: false
  congress: false
  sfc: false
  vpn: true
